name: evolution-linux
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - asteval=0.9.23=pyhd8ed1ab_0
  - blas=1.0=mkl
  - ca-certificates=2021.5.30=ha878542_0
  - certifi=2021.5.30=py37h89c1867_0
  - future=0.18.2=py37h89c1867_3
  - gmp=6.2.1=h58526e2_0
  - intel-openmp=2021.2.0=h06a4308_610
  - joblib=1.0.1=pyhd8ed1ab_0
  - keyboard=0.13.5=py37h89c1867_0
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - libblas=3.9.0=9_mkl
  - libcblas=3.9.0=9_mkl
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h2828fa1_19
  - libgfortran-ng=7.5.0=h14aa051_19
  - libgfortran4=7.5.0=h14aa051_19
  - libgomp=9.3.0=h2828fa1_19
  - liblapack=3.9.0=9_mkl
  - libllvm10=10.0.1=he513fc3_3
  - libstdcxx-ng=9.3.0=h6de172a_19
  - llvmlite=0.36.0=py37h9d7f4d0_0
  - lmfit=1.0.2=pyhd8ed1ab_0
  - metis=5.1.0=h58526e2_1006
  - mkl=2021.2.0=h06a4308_296
  - mkl-service=2.3.0=py37h27cfd23_1
  - mkl_fft=1.3.0=py37h42c9631_2
  - mkl_random=1.2.1=py37ha9443f7_2
  - mpfr=4.0.2=he80fd80_1
  - ncurses=6.2=h58526e2_4
  - numba=0.53.1=py37hb11d6e1_1
  - numpy-base=1.20.2=py37hfae3a4d_0
  - openssl=1.1.1k=h7f98852_0
  - pip=21.1.3=pyhd8ed1ab_0
  - python=3.7.10=hffdb5ce_100_cpython
  - python_abi=3.7=2_cp37m
  - readline=8.1=h46c0cb4_0
  - scikit-learn=0.24.2=py37h18a542f_0
  - scikits.odes=2.6.1=py37h33be03a_2
  - scipy=1.6.2=py37had2a1c9_1
  - setuptools=52.0.0=py37h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.36.0=h9cd32fc_0
  - suitesparse=5.10.1=hd8046ac_0
  - sundials=5.4.0=h800c78e_2
  - tbb=2020.2=h4bd325d_4
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=h21135ba_1
  - uncertainties=3.1.5=pyhd8ed1ab_0
  - wheel=0.36.2=pyhd3deb0d_0
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h516909a_1010
  - pip:
    - antimony==2.12.0.2
    - appdirs==1.4.4
    - attrs==21.2.0
    - backcall==0.2.0
    - chardet==4.0.0
    - cycler==0.10.0
    - debugpy==1.3.0
    - decorator==5.0.9
    - dnspython==2.1.0
    - idna==2.10
    - importlib-metadata==3.10.1
    - iniconfig==1.1.1
    - ipykernel==6.0.1
    - ipython==7.25.0
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - jinja2==3.0.1
    - jupyter-client==6.1.12
    - jupyter-core==4.7.1
    - kiwisolver==1.3.1
    - libroadrunner==2.0.2
    - markupsafe==2.0.1
    - matplotlib==3.4.2
    - matplotlib-inline==0.1.2
    - numpy==1.21.2
    - packaging==21.0
    - pandas==1.3.0
    - parso==0.8.2
    - pexpect==4.8.0
    - phrasedml==1.1.1
    - pickleshare==0.7.5
    - pillow==8.3.0
    - plotly==5.1.0
    - pluggy==0.13.1
    - prompt-toolkit==3.0.19
    - ptyprocess==0.7.0
    - py==1.10.0
    - pygments==2.9.0
    - pymongo==3.11.4
    - pyparsing==2.4.7
    - pytest==6.2.4
    - python-dateutil==2.8.1
    - python-libcombine==0.2.11
    - python-libnuml==1.1.4
    - python-libsbml==5.19.0
    - python-libsedml==2.0.21
    - pytz==2021.1
    - pyzmq==22.1.0
    - requests==2.25.1
    - rrplugins==2.0.4
    - sbml2matlab==1.2.3
    - tabulate==0.8.9
    - tecombine==0.2.7
    - tellurium==2.1.6
    - tenacity==7.0.0
    - tenuml==1.1.1.4
    - tesbml==5.18.1.2
    - tesedml==0.4.5.3
    - toml==0.10.2
    - tornado==6.1
    - traitlets==5.0.5
    - typing-extensions==3.10.0.0
    - urllib3==1.26.6
    - wcwidth==0.2.5
    - zipp==3.5.0
prefix: /home/hellsbells/anaconda3/envs/evolution-linux
